---
- hosts: webservers-qa
  gather_facts: no
  remote_user: jenkins
  become: yes
  tasks:
    - name: Install docker and some dependencies
      apt:
        name: python3-pip, docker.io
        state: present

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Install docker python module
      pip:
        name: docker

    - name: Create Application container
      community.docker.docker_container:
        name: docker-todoproject
        image: jackcch/todoproject:latest
        state: started
        recreate: yes
        ports:
          - "80:8000"

    - name: Collect statics - Django in container
      community.docker.docker_container_exec:
        container: docker-todoproject
        command: python3 manage.py collectstatic
        chdir: /code/todoproject/

    - name: Make Migrations - Django in container
      community.docker.docker_container_exec:
        container: docker-todoproject
        command: python3 manage.py makemigrations
        chdir: /code/todoproject/

    - name: Migrate database - Django in container
      community.docker.docker_container_exec:
        container: docker-todoproject
        command: python3 manage.py migrate
        chdir: /code/todoproject/
      register: result
        
    - name: Print Stdout
      debug:
          var: result.stdout
