def containerName="todoproject"
def tag="latest"
def dockerHubUser="jackcch"
def gitURL="https://github.com/jackcch/todoproject.git"

pipeline {
    agent any
    stages {
        stage('Build Image') {
            steps {
                echo "Stage 1 - Build Container Image"
                sh "pwd"
                sh "docker image prune -f"
                sh "docker build -t $dockerHubUser/$containerName:$tag --pull --no-cache ."
                echo "Stage 1 - Image Build Completed"
            }
        }
        stage('Push Image to Repository') {
            steps {
                echo "Stage 2a - Login DockerHub"
                withCredentials([usernamePassword(credentialsId: 'dockerHubAccount', usernameVariable: 'dockerUser', passwordVariable: 'dockerPassword')]) 
                {
                    sh ('docker login -u $dockerUser -p $dockerPassword')
                }
                echo "Stage 2 - Push Image to Repo"
                sh "docker push $dockerHubUser/$containerName:$tag"
            }
        }
        stage('Clean up Build Env') {
            steps {
                echo "Stage 3 - Cleanup"
                sh "docker rmi $dockerHubUser/$containerName:$tag"
            }
        }
        stage('Deploy') {
            steps {
                sh "ansible 192.168.1.157 -m ping -vvvv"
                ansiblePlaybook inventory: 'ci/ansible/hosts', playbook: 'ci/ansible/deploy.yaml'
            }
        }
    }
}
